#!/usr/bin/env python3
import sys
import re


width = str(80)
width_re = 'r\"\w{1,' + width + '}\"'
print(width)

dna = sys.argv[1]
def nuc_sorter(dna):
	width = sys.argv[2]

	width_re = '\w{1,' + width + '}'
	dna_clean=dna.replace('\n','')
	dna_list = re.findall(width_re,dna_clean)
	seq60 ='\n'.join(dna_list) 
	return (seq60)

#dna = """GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACC
#GTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACG
#CTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCC
#TCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAA
#TGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATG
#CCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCT
#GTCATCTTCT"""




output60 = nuc_sorter(dna)
	
print(output60)

